name: skeep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  uuid: ^3.0.7
  flutter_slidable: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  path_provider: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
      - family: Outfit
        fonts:
          - asset: lib/assets/fonts/Outfit-Thin.ttf
            weight: 100
          - asset: lib/assets/fonts/Outfit-ExtraLight.ttf
            weight: 200
          - asset: lib/assets/fonts/Outfit-Light.ttf
            weight: 300
          - asset: lib/assets/fonts/Outfit-Regular.ttf
            weight: 400
          - asset: lib/assets/fonts/Outfit-Medium.ttf
            weight: 500
          - asset: lib/assets/fonts/Outfit-SemiBold.ttf
            weight: 600
          - asset: lib/assets/fonts/Outfit-Bold.ttf
            weight: 700
          - asset: lib/assets/fonts/Outfit-ExtraBold.ttf
            weight: 800
          - asset: lib/assets/fonts/Outfit-Black.ttf
            weight: 900

